package org.appinventor;
import com.google.appinventor.components.runtime.HandlesEventDispatching;
import com.google.appinventor.components.runtime.EventDispatcher;
import com.google.appinventor.components.runtime.Form;
import com.google.appinventor.components.runtime.Component;
import com.google.appinventor.components.runtime.HorizontalArrangement;
import com.google.appinventor.components.runtime.Label;
import com.google.appinventor.components.runtime.Image;
import com.google.appinventor.components.runtime.Button;
import com.google.appinventor.components.runtime.TextBox;
import com.google.appinventor.components.runtime.Notifier;
import com.google.appinventor.components.runtime.Clock;
import com.google.appinventor.components.runtime.TinyDB;
class Screen1 extends Form implements HandlesEventDispatching {
  private HorizontalArrangement Savings_Bar;
  private Label savings_text;
  private Label savings;
  private Image savingsbar_image;
  private Button updatesavings;
  private HorizontalArrangement Life_Bar;
  private Label life_text;
  private HorizontalArrangement lives;
  private Image life1;
  private Image life2;
  private Image life3;
  private Image life4;
  private Image life5;
  private Image life6;
  private Button updatelives;
  private Label quiz_label;
  private Label question1;
  private HorizontalArrangement Q1A1;
  private Button Quiz_1_Option_A;
  private Label Label4;
  private HorizontalArrangement Q1A2;
  private Button Quiz_1_Option_B;
  private Label Label5;
  private HorizontalArrangement Q1A3;
  private Button Quiz_1_Option_C;
  private Label Label6;
  private HorizontalArrangement Q1A4;
  private Button Quiz_1_Option_D;
  private Label Label7;
  private Label question2;
  private HorizontalArrangement Q2A1;
  private Button Quiz_2_Option_A;
  private Label Label8;
  private HorizontalArrangement Q2A2;
  private Button Quiz_2_Option_B;
  private Label Label9;
  private HorizontalArrangement Q2A3;
  private Button Quiz_2_Option_C;
  private Label Label10;
  private HorizontalArrangement Q2A4;
  private Button Quiz_2_Option_D;
  private Label Label11;
  private Label incomePercentLabel;
  private HorizontalArrangement HorizontalArrangement1;
  private TextBox incomePercentBox;
  private Button enterIncomePercentButton;
  private Notifier Notifier1;
  private Clock Clock1;
  private Clock billClock;
  private TinyDB TinyDB1;
  private Clock realTimeClock;
  protected void $define() {
    this.AppName("hackathon");
    this.BackgroundColor(0xFF888888);
    this.Scrollable(true);
    this.Title("Screen1");
    Savings_Bar = new HorizontalArrangement(this);
    savings_text = new Label(Savings_Bar);
    savings_text.Text("Amount Saved: ");
    savings = new Label(Savings_Bar);
    savings.Text("0");
    savingsbar_image = new Image(this);
    savingsbar_image.Height(50);
    savingsbar_image.Width(300);
    savingsbar_image.Picture("ScreenShot2022-02-12at11.05.15PM.png");
    savingsbar_image.RotationAngle(0);
    updatesavings = new Button(this);
    updatesavings.Text("Update Savings");
    Life_Bar = new HorizontalArrangement(this);
    life_text = new Label(Life_Bar);
    life_text.FontTypeface(1);
    life_text.Text("Life Level :  ");
    lives = new HorizontalArrangement(this);
    lives.BackgroundColor(0x00FFFFFF);
    lives.Height(-1006);
    life1 = new Image(lives);
    life1.Height(-1005);
    life1.Width(-1010);
    life1.Picture("life_heart.png");
    life2 = new Image(lives);
    life2.Height(-1005);
    life2.Width(-1010);
    life2.Picture("life_heart.png");
    life3 = new Image(lives);
    life3.Height(-1005);
    life3.Width(-1010);
    life3.Picture("life_heart.png");
    life4 = new Image(lives);
    life4.Height(-1005);
    life4.Width(-1010);
    life4.Picture("life_heart.png");
    life5 = new Image(lives);
    life5.Height(-1005);
    life5.Width(-1010);
    life5.Picture("life_heart.png");
    life6 = new Image(lives);
    life6.Height(-1005);
    life6.Width(-1010);
    life6.Picture("life_heart.png");
    updatelives = new Button(this);
    updatelives.Text("Update Lives");
    quiz_label = new Label(this);
    quiz_label.FontBold(true);
    quiz_label.FontSize(50);
    quiz_label.Text("Quiz 1");
    question1 = new Label(this);
    question1.Text("If you invest $4000 and get 2% interest compounded \n monthly, how much will you have after 10 years?");
    Q1A1 = new HorizontalArrangement(this);
    Quiz_1_Option_A = new Button(Q1A1);
    Quiz_1_Option_A.Text("A");
    Label4 = new Label(Q1A1);
    Label4.Text("$200.50");
    Q1A2 = new HorizontalArrangement(this);
    Quiz_1_Option_B = new Button(Q1A2);
    Quiz_1_Option_B.Text("B");
    Label5 = new Label(Q1A2);
    Label5.Text("$1148.72");
    Q1A3 = new HorizontalArrangement(this);
    Quiz_1_Option_C = new Button(Q1A3);
    Quiz_1_Option_C.Text("C");
    Label6 = new Label(Q1A3);
    Label6.Text("$5025.99");
    Q1A4 = new HorizontalArrangement(this);
    Quiz_1_Option_D = new Button(Q1A4);
    Quiz_1_Option_D.Text("D");
    Label7 = new Label(Q1A4);
    Label7.Text("$4884.40");
    question2 = new Label(this);
    question2.Text("At least what percent of your income should you save?");
    Q2A1 = new HorizontalArrangement(this);
    Quiz_2_Option_A = new Button(Q2A1);
    Quiz_2_Option_A.Text("A");
    Label8 = new Label(Q2A1);
    Label8.Text("5%");
    Q2A2 = new HorizontalArrangement(this);
    Quiz_2_Option_B = new Button(Q2A2);
    Quiz_2_Option_B.Text("B");
    Label9 = new Label(Q2A2);
    Label9.Text("10%");
    Q2A3 = new HorizontalArrangement(this);
    Quiz_2_Option_C = new Button(Q2A3);
    Quiz_2_Option_C.Text("C");
    Label10 = new Label(Q2A3);
    Label10.Text("15%");
    Q2A4 = new HorizontalArrangement(this);
    Quiz_2_Option_D = new Button(Q2A4);
    Quiz_2_Option_D.Text("D");
    Label11 = new Label(Q2A4);
    Label11.Text("20%");
    incomePercentLabel = new Label(this);
    incomePercentLabel.Text("Please enter as decimal what percent of your income \n you would like to save:");
    HorizontalArrangement1 = new HorizontalArrangement(this);
    incomePercentBox = new TextBox(HorizontalArrangement1);
    incomePercentBox.Hint("Hint for TextBox1");
    enterIncomePercentButton = new Button(HorizontalArrangement1);
    enterIncomePercentButton.Text("Enter");
    Notifier1 = new Notifier(this);
    Clock1 = new Clock(this);
    Clock1.TimerInterval(60000);
    billClock = new Clock(this);
    billClock.TimerInterval(120000);
    TinyDB1 = new TinyDB(this);
    realTimeClock = new Clock(this);
  }
  public boolean dispatchEvent(Component component, String componentName, String eventName, Object[] params){
    return false;
  }
}